### ISSUE TITLE
Python unit test

### ISSUE THREAD

**Issue by shevamomoko** [o3project/odenos#123]
Hi, I'm new for this and I have followed the quickstart manual to install odenos on my server.
But it seems that I can't pass the python unit test. Could anyone kindly give me some advises on this?
Thank you in advance!

Error message(during python unit test):

ERROR:root:Traceback (most recent call last):
  File "/home/sheva/odenos/src/main/python/org/o3project/odenos/remoteobject/transport/message_dispatcher.py", line 153, in __redisSubscriberRunnable
    channel = mesg['channel']
KeyError: 'channel'

**Comment by araobp** [comment]
Thank you for reporting the bug.

The error shows that the message as Python dict received from Redis does not contain the key "channel".

The test script and also others in the directory seem to be broken, due to the several modifications made after the first release of ODENOS.

I will try to fix those broken test scripts.

**Comment by araobp** [comment]
Fixed by #132.
